name: Upload Release Assets
on:
  release:
    types:
      - published
      
jobs: 
  api: 
    name: Release Api
    uses: ./.github/workflows/ReleaseApi.yml

  web:
    name: Release Web
    uses: ./.github/workflows/ReleaseWeb.yml
